pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('jenkins_aws_access_key')
        AWS_SECRET_ACCESS_KEY = credentials('jenkins_aws_secret_key')
        AWS_REGION = "${AWS_REGION}"
    }
    stages {
        stage('Checkout'){
            steps {
                checkout scm
            }
        }
        stage('Validate configuration'){
            steps {
                dir ('base'){
                    sh "echo ${AWS_REGION}"
                    sh "sudo packer validate base_ebs.json"
                }
            }
        }
        stage('Create base image'){
            steps {
                dir ('base'){
                    sh "sudo packer build base_ebs.json"
                }
            }
        }
    }
}
