pipeline {
    agent any
    stages {
        stage('Checkout'){
            steps {
                checkout scm
            }
        }
        stage('Validate configuration'){
            steps {
                dir ('base'){
                    withCredentials([string(credentialsId: 'jenkins_aws_access_key', variable: 'ACCESS_KEY'),
                                     string(credentialsId: 'jenkins_aws_secret_key', variable: 'SECRET_KEY')]){
                        sh "sudo packer validate \
                            -var 'aws_access_key=$ACCESS_KEY' \
                            -var 'aws_secret_key=$SECRET_KEY' \
                            -var 'aws_region=${AWS_REGION}' \
                            base_ebs.json"
                    }
                }
            }
        }
        stage('Create base image'){
            steps {
                dir ('base'){
                    withCredentials([string(credentialsId: 'jenkins_aws_access_key', variable: 'ACCESS_KEY'),
                                     string(credentialsId: 'jenkins_aws_secret_key', variable: 'SECRET_KEY')]){
                        sh "sudo packer build \
                            -var 'aws_access_key=$ACCESS_KEY' \
                            -var 'aws_secret_key=$SECRET_KEY' \
                            -var 'aws_region=${AWS_REGION}' \
                            base_ebs.json"
                    }
                }
            }
        }
    }
}
